version: '3.8'

services:
  trattoria-menu:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - DATA_DIR=/app/data
    restart: unless-stopped
    container_name: trattoria-menu-manager

volumes:
  data:
    driver: local
